### ISSUE TITLE
How to deal with "Invalid rune in input data"

### ISSUE THREAD

**Issue by suntong** [spakin/awk#12] opened 2017-07-22 13:53 UTC
My https://github.com/suntong/fss deal with string feed directly from `mlocate`, which return file names from the file system. 

Sometimes such feed does contain some "invalid" runes, how can I deal with them? 

Here is a minimum data set I've isolated:

```
$ cat /tmp/test
210 - A Present for Santa
212 - Pinto, the Pony Express
214 - The Big PiAñata
216 - Super Map

$ cat /tmp/test | fss dirs
1 2 Invalid rune in input data
# The `1 2 ` comes from `print(s.NR)`
# and the error comes from the `214 - The Big PiAñata` line.

# Note that if I copy and try that line directly on command line, it'll work normally:
{ echo 'The Big PiAñata'; echo 'The Big PiAñata'; echo 'The Big PiAñata'; } | fss dirs
1 2 3 
```

I finally found that the problem is not the `ñ` but how it was coded:

```
$ echo 'The Big PiAñata' | hexdump -C
00000000  54 68 65 20 42 69 67 20  50 69 41 c3 b1 61 74 61  |The Big PiA..ata|

$ cat /tmp/test | hexdump -C
00000000  32 31 30 20 2d 20 41 20  50 72 65 73 65 6e 74 20  |210 - A Present |
00000010  66 6f 72 20 53 61 6e 74  61 0a 32 31 32 20 2d 20  |for Santa.212 - |
00000020  50 69 6e 74 6f 2c 20 74  68 65 20 50 6f 6e 79 20  |Pinto, the Pony |
00000030  45 78 70 72 65 73 73 0a  32 31 34 20 2d 20 54 68  |Express.214 - Th|
00000040  65 20 42 69 67 20 50 69  41 f1 61 74 61 0a 32 31  |e Big PiA.ata.21|
00000050  36 20 2d 20 53 75 70 65  72 20 4d 61 70 0a        |6 - Super Map.|
```

Note the "41 **f1** 61", that's what causing the problem. 

how can I deal with it?
Please advice. 

Thanks

**Comment by suntong** [comment] 2017-07-22 14:17
This also give a reasonable explanation to #6, I believe the problem he is having is that the Chinese are encoded using GB2312 encoding, not utf. Each GB2312 encoded Chinese takes two bytes, each byte has the 8th bit set to `1`.

**Comment by suntong** [comment] 2017-07-22 14:25
[test.txt](https://github.com/spakin/awk/files/1167407/test.txt)

**Comment by suntong** [comment] 2017-07-22 15:20
[test2.txt](https://github.com/spakin/awk/files/1167438/test2.txt)


```
$ cat /tmp/test2.txt | hexdump -C
00000000  47 61 6c 6c 6f 20 63 65  6c 74 69 63 6f 0a 47 65  |Gallo celtico.Ge|
00000010  73 97 20 42 61 6d 62 69  6e 6f 0a                 |s. Bambino.|
```

**Comment by spakin** [comment] 2017-07-24 04:50
I'm not sure what can be done when the input contains an invalid character.  I suppose I could introduce a method on `awk.Script` that says to ignore invalid runes, but I admit I don't know how to recover from an invalid rune.  Any suggestions?

**Comment by suntong** [comment] 2017-07-24 13:38
Me neither unfortunately. Ignoring the invalid runes and let the script continue is a viable option. 

Is it caused by the `s.F(0).String()` calling? If so, then another option might be to provide a none-awk function `.Bytes()`, so as for the end users to handle exceptions themselves. 

just a thought.

**Comment by spakin** [comment] 2017-07-24 15:42
> Is it caused by the s.F(0).String() calling? If so, then another option might be to provide a none-awk function .Bytes(), so as for the end users to handle exceptions themselves.

Unfortunately, no. It occurs much earlier, when the input stream is scanned for a record terminator.  That makes recovery extremely tricky because a bad rune could make a non-record terminator look like a record terminator or vice versa.

**Comment by suntong** [comment] 2017-07-24 15:46
Then, would it be possible just to treat the input as `[]byte` as oppose to `[]rune`? It's very unlikely for any one to use a utf8 code as the record terminator,

**Comment by spakin** [comment] 2017-07-24 17:18
Without the ability to automatically split an input stream into records and fields, there's a lot less point to using the `awk` package to begin with.

I'll see if I can find a way to drop bad runes automatically, even in a best-effort sense.  If not, it may be possible to let programs specify a callback function that will take erroneous input, correct the first―and only the first―bad rune and return the corrected input.  Does that sound reasonable?

**Comment by suntong** [comment] 2017-07-24 20:00
Yeah, quite agree. automatically splitting input stream into records is a must. 

Hmm..., let me think about it, because what you are describing is quite "invasive", that I wouldn't wishing happening to my own code, :-)

**Comment by suntong** [comment] 2017-07-24 20:22
There are two places that give the error, one is from `makeSingleCharFieldSplitter`
https://github.com/spakin/awk/blob/master/script.go#L530
and the other is from `makeRecordSplitter`
https://github.com/spakin/awk/blob/master/script.go#L718

which is the one causing this problem, the `makeRecordSplitter` one?

**Comment by suntong** [comment] 2017-07-24 20:39
Hmm, in either place, the code assumes the separator character is **utf** rune, and treats input as **utf** runes. 

This is what I meant to change, because I presume 99% of the cases are that the input separators are, space, tab, comma, "|", etc, i.e., all are normal ascii characters, that treating the input as `[]byte` would be good enough. 

So I personally think that, if we can define an extra flag, _separator character is utf_, and the awk script user will only set it when indeed the separator character(s) is/are utf, and use the existing code only under such condition. Otherwise, treat separator character and input just like `[]byte` and do a normal `[]byte` scan instead of utf code scan. 

The code looks to be doubled in the above particular part, but I would presume it will actually speed up the processing over 99% of the time.

**Comment by suntong** [comment] 2017-07-24 20:51
This, https://play.golang.org/p/pygXyb2rap, in only using strings.Split, but I believe it'd still work if we treat it like `[]byte`

```
package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Println("Hello, playground")
	fmt.Printf("%q\n", strings.Split("a,b,c", ","))
	fmt.Printf("%q\n", strings.Split("你,好,世,界", ","))
}
```

**Comment by spakin** [comment] 2017-07-25 06:05
> So I personally think that, if we can define an extra flag, _separator character is utf_, and the awk script user will only set it when indeed the separator character(s) is/are utf, and use the existing code only under such condition. Otherwise, treat separator character and input just like `[]byte` and do a normal `[]byte` scan instead of utf code scan. 

Won't that merely delay the problem?  At some point, most programs will try to access the fields and blow up because they contain invalid UTF-8 runes, won't they?

**Comment by suntong** [comment] 2017-07-25 13:33
Oh, yeah, indeed that's a concern. I was thinking that providing a none-awk function `.Bytes()`, so as for the end users to handle exceptions themselves would solve the problem, but there maybe intermediate steps within awk that I'm not aware of. 

Alright, I'll shut up and let you decide what's the best fix then. 

Thx.

**Comment by suntong** [comment] 2017-07-25 13:52
Did a lot of reading, and only this seems to be slightly helpful, 
https://groups.google.com/forum/#!topic/golang-nuts/4hvipzyKJtI

> Every invalid code points in a sequence will be converted to 0xFFFD

I think that's cleaner than a callback function to the user space. 


https://stackoverflow.com/questions/20401873/remove-invalid-utf-8-characters-from-a-string-go-lang  
http://www.tysonmaly.com/programming/go/process-xml-invalid-utf-8-go/  
https://github.com/golang/go/issues/11527  
https://github.com/golang/go/issues/11185  
https://github.com/golang/lint/issues/252

**Comment by spakin** [comment] 2017-07-26 05:25
Upon further investigation, it seems that invalid runes aren't as devastating as I had thought; Go may be able to recover on its own.  Try commenting out lines [530](https://github.com/spakin/awk/blob/178b98f93e8f55fcbb0434436080c3aeb523f5d8/script.go#L530) and [718](https://github.com/spakin/awk/blob/178b98f93e8f55fcbb0434436080c3aeb523f5d8/script.go#L718) in [`script.go`](https://github.com/spakin/awk/blob/178b98f93e8f55fcbb0434436080c3aeb523f5d8/script.go) (the two `Invalid rune in input data` lines) and seeing if that's all it takes to get `awk` to continue in light of errors.  If so, I'll remove those lines from the file.

**Comment by suntong** [comment] 2017-07-26 13:21
Marvelous! All my existing tests passed!
What a nice surprise to have such a simple and excellent solution!

Let me do more testing before closing it...

**Comment by suntong** [comment] 2017-07-26 14:47
**Before** change:

```
$ echo "你,好,世,界" | tee /tmp/cc.utf.txt | autogb -i utf8 -o gb > /tmp/cc.gb.txt

$ cat /tmp/cc.gb.txt | hexdump -C
00000000  c4 e3 2c ba c3 2c ca c0  2c bd e7 0a              |..,..,..,...|

$ cat /tmp/cc.utf.txt | awk -F, '{print $3 $4}'
世界

$ cat /tmp/cc.gb.txt | awk -F, '{print $3 $4}' | hexdump -C
00000000  ca c0 bd e7 0a                                    |.....|

# If view under GB2312/GB18030 Encoding
$ cat /tmp/cc.gb.txt
你,好,世,界

$ cat /tmp/cc.gb.txt | awk -F, '{print $3 $4}'
世界

# So, ====> awk works for both cases, i.e., not imposing the unicode encoding at all.

$ cat /tmp/cc.utf.txt | go run  Example11B.go
世 界

# same if run under either GB2312/GB18030 Encoding or Unicode 
$ cat /tmp/cc.gb.txt | go run  Example11B.go
panic: Invalid rune in input data

goroutine 1 [running]:
main.main()
	/.../Go/src/text/awk/Example11B.go:24 +0x3da
exit status 2

# So, ====> go-awk only works for utf case
```

**After** change:

```
# same if run under either GB2312/GB18030 Encoding or Unicode 
$ cat /tmp/cc.gb.txt | go run  Example11B.go | wc 
      0       0       0

$ cat /tmp/cc.utf.txt | go run  Example11B.go
世 界

# So, ====> the change does not work for fields separation. 


```

Here are the test files, 

- [cc.utf.txt](https://github.com/spakin/awk/files/1176942/cc.utf.txt)
- [cc.gb.txt](https://github.com/spakin/awk/files/1176944/cc.gb.txt)

and the `Example11B.go` is at, 
https://github.com/suntong/lang/blob/master/lang/Go/src/text/awk/Example11B.go

**Comment by spakin** [comment] 2017-07-27 05:35
My hypothesis is that `awk` is not robust to the last character in a record being invalid.  As I don't have GB2312/GB18030 set up on my system, could you please replace both occurrences of `utf8.UTFMax` in `script.go` with `width`, and let me know if that fixes the problem?

**Comment by suntong** [comment] 2017-07-27 19:39
One step forward, but not totally solve it:

```
$ cat /tmp/cc.gb.txt | go run  Example11B.go | hexdump -C
00000000  ca c0 20 0a                                       |.. .|
```

I.e., one character get output, but not the second one. 

You actually don't need to have GB2312/GB18030 set up on your system to test it. Just run it like I run it above. If all works well, the `hexdump` output should be 

`ca c0 20 bd e7 0a`

corresponding to the `cc.gb.txt` input.

**Comment by spakin** [comment] 2017-07-28 04:43
I think I know what the problem is.  The [`SplitFunc`](https://golang.org/pkg/bufio/#SplitFunc)s that `awk` defines request more data if the current buffer ends with an invalid rune, the assumption being that a partial rune was read, and a few more bytes are needed to complete it.  However, these functions don't account for the case in which the final rune truly is complete yet is nevertheless invalid.

I believe the solution is merely not to request more data when at EOF.  I pushed out the code for this to a new, temporary branch called [`invalid-runes`](https://github.com/spakin/awk/tree/invalid-runes).  Please download that branch and let me know if `awk` can finally handle non-UTF-8 input as expected.

**Comment by suntong** [comment] 2017-07-28 13:26
Hm, looks good!

Under `LANG=zh_CN.UTF-8`:

    echo "a你,a好b,世bb,界" | tee -a /tmp/cc.utf.txt | autogb -i utf8 -o gb >> /tmp/cc.gb.txt

Under `LANG=zh_CN.GB18030`:

```
$ cat /tmp/cc.gb.txt | go run  Example11B.go 
你 好 世 界
a你 a好b 世bb 界
```

Seems to be working fine.  
Is there any other end cases you can think of that we should cover? Thx.

**Comment by spakin** [comment] 2017-07-29 04:02
> Seems to be working fine.
> Is there any other end cases you can think of that we should cover? Thx.

I can't think of anything offhand, but let me know if you run into any new problems.

I'll go ahead and merge the `invalid-runes` branch into `master` then close this issue.

Thanks for reporting the issue with invalid runes and helping test the fix.

**Closed** 2017-07-29 04:04 UTC

**Comment by suntong** [comment] 2017-07-29 04:09
:+1:
